### ISSUE TITLE
Requiring autoload.php in the Validator class

### ISSUE THREAD

**Issue by MusikAnimal** [theresnotime/php-ipa-validator#4]
When installing packages with composer, they don't seem to normally have their own autoload.php. [Validator.php#L13](https://github.com/theresnotime/php-ipa-validator/blob/dee8438682485469bf13fdfe3d86ea39e4ec80c4/src/Validator.php#L13) explicitly requires the autoload.php to be present, so I'm not able to use the package in a 'host' application (in our case Phonos). I get the error:

`Uncaught require_once(/var/www/html/w/extensions/Phonos/vendor/theresnotime/ipa-validator/src/../vendor/autoload.php): failed to open stream: No such file or directory`

Reviewing php-ipa-validator's composer.json, it seems it doesn't have any non-dev requirements, so there's nothing it needs to load anyway?

I've never created a composer package before, so please forgive my ignorance if I'm missing something!

**Comment by theresnotime** [comment]
> I've never created a composer package before, so please forgive my ignorance if I'm missing something!

Nor have I! I followed a tutorial perhaps a little too closely — I've removed the autoload and the tests still pass 🎉
